name: 2021-11-fennec-fox
channels:
  - defaults
  - conda-forge
  - foxbms
dependencies:
  - pandoc
  - pip
  - python=3.9
  - zlib
  - wxpython
  - pip:
      - appdirs
      - babel
      - black
      - bokeh
      - cantools[plot]
      - cffconvert
      - click
      - colorama
      - coverage
      - crcmod
      - dask
      - docutils
      - doorstop==2.2b5
      - filterpy
      - gcovr
      - gitdb
      - gitpython
      - gprof2dot
      - ipython
      - isort
      - jinja2
      - joblib
      - jsonschema
      - jupyter
      - matplotlib
      - mypy
      - mypy-extensions
      - nbclient
      - nbconvert
      - nbformat
      - numpy
      - openpyxl
      - pandas
      - pandas-stubs
      - pandocfilters
      - pip-licenses
      - plantuml
      - plantuml-markdown
      - plotly
      - prompt-toolkit
      - psutil
      - pybtex
      - pybtex-docutils
      - pycparser
      - pyenchant
      - pylint
      - pyserial
      - pysimplegui
      - python-can==4.0.0.dev2
      - python-dateutil
      - python-lin
      - python-markdown-math
      - python-uds
      - pyvisa
      - pyyaml
      - pyzmq
      - requests
      - rope
      - rsinstrument
      - ruamel-yaml
      - ruamel-yaml-clib
      - scikit-learn
      - scipy
      - seaborn
      - sphinx
      - sphinx-copybutton
      - sphinx-plotly-directive
      - sphinx-rtd-theme
      - sphinxcontrib-applehelp
      - sphinxcontrib-bibtex
      - sphinxcontrib-devhelp
      - sphinxcontrib-htmlhelp
      - sphinxcontrib-jsmath
      - sphinxcontrib-mermaid
      - sphinxcontrib-needs
      - sphinxcontrib-plantuml
      - sphinxcontrib-serializinghtml
      - sphinxcontrib-spelling
      - statsmodels
      - strictdoc
      - tabulate
      - toml
      - typing-extensions
      - uptime
      - widgetsnbextension
