# Copyright (c) 2010 - 2021, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

---
##############################################################################
# Important:                                                                 #
# Paths must be given as seen from the build variant root directory          #
##############################################################################

:project:
  :use_exceptions: TRUE
  :use_test_preprocessor: TRUE
  :use_mocks: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: .
  :test_file_prefix: test_
  :which_ceedling: ../../tools/vendor/ceedling
  :ceedling_version: 0.31.1
  :default_tasks:
    - test:all

:environment: []

:extension:
  :executable: .out

:paths:
  :test:
    - +:../../tests/unit/**
    - -:../../tests/unit/support
  :source:
    - ../../src/app/**
    - ../../src/opt/**
  :include:
    - +:./include/**
    - +:../../src/**
    - -:../../src/app/**
    - -:../../src/opt/**
  :support:
    - ../../tests/unit/support/**

:defines:
  :common: &common_defines
    - UNITY_UNIT_TEST
    - ASSERT_LEVEL=2
    - UNITY_INCLUDE_EXEC_TIME
    - FOXBMS_USES_FREERTOS=1
  :test:
    - *common_defines
  :test_preprocess:
    - *common_defines
    - INC_FREERTOS_H

:cmock:
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :mock_prefix: Mock
  :weak: ""
  :strippables:
    [
      "(.FREERTOS_SYSTEM_CALL)",
      "(.PRIVILEGED_FUNCTION)",
      "(portDONT_DISCARD)",
      "(?:TEST_LTC_DECLARE_GET\\s*\\(+.*?\\)+)",
      "(?:TEST_LTC_DEFINE_GET\\s*\\(+.*?\\)+)",
    ]
  :includes:
    - "FreeRTOSConfig.h"
    - "FreeRTOS.h"
    - "portmacro.h"
    - "mpu_wrappers.h"
    - "portable.h"
    - "task.h"
    - "queue.h"
    - "semphr.h"
    - "stream_buffer.h"
    - "event_groups.h"
    - "string.h"
  :plugins:
    - :ignore
    - :callback
    - :ignore_arg
    - :return_thru_ptr
  :treat_externs: :include
  :treat_as:
    uint8: HEX8
    uint16: HEX16
    uint32: UINT32
    int8: INT8
    bool: UINT8

#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

:tools_test_linker:
  :arguments:
    - -lm
    - -flto
:tools_gcov_linker:
  :arguments:
    - -lm
    - -flto
:gcov:
  :utilities:
    - gcovr
  :reports:
    - HtmlDetailed
    - Text
    - Cobertura
  :abort_on_uncovered: true
  :uncovered_ignore_list:
    - "../../src/app/driver/imd/bender/ir155/bender_ir155.c"
    - "../../src/app/driver/imd/bender/iso165c/bender_iso165c.c"
    - "../../src/app/driver/sbc/fs8x_driver/sbc_fs8x.c"
    - "../../src/app/driver/sbc/fs8x_driver/sbc_fs8x_communication.c"
    - "../../src/app/main/main.c"
    - "../../src/app/main/fstartup.c"
  :gcovr:
    :report_root: "../../"
    :report_exclude: ".*vendor.*|.*build.*|.*test.*|.*tests.*|.*lib.*|.*Test.*|.*src.hal.*|.*src.os.*"
    :exclude_directories: ".*tests.*|.*src.os.*|.*build.*|.*src.app.driver.sbc.fs8x_driver."
    :sort_percentage: true
    :sort_uncovered: false
    :html_medium_threshold: 60
    :html_high_threshold: 85
    :print_summary: true
    :num_parallel_threads: 4
    :keep: false

:junit_tests_report:
  :artifact_filename: report_junit.xml

:plugins:
  :load_paths:
    - ../../tools/vendor/ceedling/plugins
  :enabled:
    - gcov
    - stdout_pretty_tests_report
    - module_generator
    - xml_tests_report
    - junit_tests_report
